#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DevUiAndroidV2.Resource", IsApplication=true)]

namespace DevUiAndroidV2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int squadType = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int BottomLayout = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int battleView = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int cocosLayout = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int doSomethingButton = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int enemyDamageText = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout2 = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout3 = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int loadLastGame = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int rankSeekBar = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int rankText = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int rowText = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int rowsSeekBar = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int squadTypeSpinner = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int startGameButton = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int textView1 = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int textView3 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int textView4 = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int topLayout = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int totalInSquad = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int totalUnits = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int winnerText = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int yourDamageText = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int BattleView = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PrepareView = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ResultView = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
